# Generated by Django 2.1.7 on 2019-08-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
                ('ip', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=30)),
                ('user_type', models.IntegerField(default=0)),
                ('class_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('department', models.CharField(choices=[('media', 'media'), ('cad', 'cad'), ('hi_perf', 'hi_perf'), ('ai', 'ai'), ('software', 'software'), ('network', 'network'), ('gix', 'gix'), ('cs_ma', 'cs_ma')], max_length=15)),
                ('student_type', models.CharField(choices=[('master', 'master'), ('doctor_straight', 'doctor_straight'), ('master_doctor', 'master_doctor'), ('doctor_normal', 'doctor_normal')], max_length=25)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('above', 'above')], max_length=10)),
                ('student_status', models.CharField(choices=[('cst', 'cst'), ('shenzhen', 'shenzhen'), ('other', 'other')], max_length=10)),
                ('political_status', models.CharField(choices=[('party', 'party'), ('pre_party', 'pre_party'), ('league', 'league'), ('general', 'general'), ('other', 'other')], max_length=15)),
                ('ethnic_group', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=20)),
                ('is_project_started', models.BooleanField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('apply_id', models.IntegerField(default=0)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.User'),
        ),
    ]
