# Generated by Django 2.1.4 on 2019-09-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyinfo',
            name='extra_score',
            field=models.FloatField(default=0),
        ),
    ]
