# Generated by Django 2.1.4 on 2019-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_apply_info_teacher_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherscore',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
